name = "apipost-rs"
product-name = "ApiPost-Rs"
version = "0.1.0"
identifier = "com.apipost-rs.apipost-rs"
description = "A Postman alternative built with Rust and gpui"
homepage = "https://github.com/apipost-rs/apipost-rs"
publisher = "apipost-rs team"
license-file = "LICENSE"
copyright = "Copyright 2025 apipost-rs team"
category = "Development"

icons = [
    "assets/icon.png",
]

out-dir = "./dist"
binaries = [{ path = "apipost-rs", main = true }]
binaries-dir = "target/release"

[linux]
generate-desktop-entry = true

[deb]
depends = ["libwebkit2gtk-4.1-0", "libgtk-3-0", "libglib2.0-0", "libc6", "libx11-6", "libwayland-client0"]
section = "utils"
priority = "optional"
maintainer = "Lidong yang <735615901@qq.com>"

[nsis]
installer-mode = "currentUser"
